### ISSUE TITLE
* /write: unable to open file 

### ISSUE THREAD

**Issue by ghost** [MaS0uD/mBOT#3]
When I connect to a server (EFNet) the following error occurs:

`* /write: unable to open file 'C:\Users\acvxq\AppData\Roaming\mbot\Sys\mBOT\SNotices\11-03-2017.txt' (line 819, Events.mrc)`

At first glance: 
```
var %file = $mB.Dir($+(mBOT\SNotices\,%Log.Date,.txt)).qt
if (!$exists(%file)) {
  .write -c $qt(%file)
```
Directory _SNotices_ does not exist. If I manually create it, the error disappears.

**Comment by MaS0uD** [comment]
I cannot reporduce this issue.
Why is it being executed from Roaming? Try putting everything in the root directory of C:\ or another drive and see if the problem consists.

**Comment by ghost** [comment]
If I download mBot-master.zip from GitHub and put mBot in C:\ and copy mirc.exe to it I still get the following error upon connecting: 
```
* /write: unable to open file 'C:\mBOT-master\Sys\mBOT\SNotices\11-03-2017.txt' (line 819, Events.mrc)
```
Due to the folder _SNotices_ not existing in the \Sys\mBOT\ directory. Minor issue, but I figured I report it!

N.B.:
As for your question why is it being executed from roaming. I put all scripts I have in %appdata% and then create a custom shortcut:
`c:\program files (x86)\mirc\mirc.exe -r%appdata%\scriptname`

**Comment by MaS0uD** [comment]
Thanks for the report, yeah it is due to the SNotice directory not being there. After all this time one would imagine that either mIRC or Windows itself would handle such thing and create the directory if it doesn't exist.
I've added a check to create the directory manually if it's not there.
